/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package simcoviewer.ui;

import javax.swing.JTable;
import simcoviewer.datatypes.Cache;
import simcoviewer.ui.tablemodels.CacheViewerTableModel;

/**
 *
 * @author fede
 */
public class CacheViewerJF extends CycleViewerJF{

    public Cache cache;
    
    public CacheViewerJF(Cache cache, long currentCycle) {   
        super();
        initComponents();
        this.cache = cache;
        this.setTitle(cache.getName());
        tblCacheViewer.setModel(new CacheViewerTableModel(cache.getCacheLineList(currentCycle)));
        // Line Number Size
        tblCacheViewer.getColumnModel().getColumn(0).setWidth(50);
        tblCacheViewer.getColumnModel().getColumn(0).setMinWidth(50);
        tblCacheViewer.getColumnModel().getColumn(0).setMaxWidth(50);
        tblCacheViewer.getColumnModel().getColumn(0).setResizable(false);
        tblCacheViewer.getColumnModel().getColumn(1).setWidth(50);
        tblCacheViewer.getColumnModel().getColumn(1).setMinWidth(50);
        tblCacheViewer.getColumnModel().getColumn(1).setMaxWidth(50);
        tblCacheViewer.getColumnModel().getColumn(1).setResizable(false);
        tblCacheViewer.getColumnModel().getColumn(2).setWidth(70);
        tblCacheViewer.getColumnModel().getColumn(2).setMinWidth(70);
        tblCacheViewer.getColumnModel().getColumn(2).setMaxWidth(70);
        tblCacheViewer.getColumnModel().getColumn(2).setResizable(false);
        tblCacheViewer.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
    }

    @Override
    public void setCurrentCycle(long cycle){
        CacheViewerTableModel cvtm = (CacheViewerTableModel) tblCacheViewer.getModel();
        cvtm.setCacheLineList(cache.getCacheLineList(cycle));
        cvtm.fireTableDataChanged();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCacheViewer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        tblCacheViewer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCacheViewer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCacheViewer;
    // End of variables declaration//GEN-END:variables
}
