/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package simcoviewer.ui;

import simcoviewer.datatypes.processor.Processor;
import simcoviewer.datatypes.processor.ProcessorState;

/**
 *
 * @author fede
 */
public class SimpleUnpipedProcessorViewerJF extends CycleViewerJF {

    private Processor processor;
    
    /**
     * Creates new form SiimpleUnpipedProcessorViewerJF
     */
    public SimpleUnpipedProcessorViewerJF(Processor proc) {        
        initComponents();
        this.processor = proc;
        this.setTitle(processor.getProcessorName());
        
    }

    @Override
    public void setCurrentCycle(long currentCycle) {
        ProcessorState cycleState = processor.getCycleProcessorState(currentCycle);
        if (cycleState != null){
            long pcValue = cycleState.getPcValue();
            txtProgramCounter.setText(String.format("0x%08X", pcValue));
            txtInstructionRegister.setText(cycleState.getIrValue());
            txtFlagsRegister.setText("Z = " + cycleState.getzFlag() + "    N =  " + cycleState.getnFlag()
                    + "    C = " + cycleState.getcFlag() + "    V = " + cycleState.getvFlag());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProgramCounter = new javax.swing.JLabel();
        lblInstructionRegister = new javax.swing.JLabel();
        lblFlagsRegister = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProgramableRegisters = new javax.swing.JTable();
        txtInstructionRegister = new javax.swing.JTextField();
        txtProgramCounter = new javax.swing.JTextField();
        lblProgramableRegisters = new javax.swing.JLabel();
        txtFlagsRegister = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        lblProgramCounter.setText("Program Counter: ");

        lblInstructionRegister.setText("Instruction Register: ");

        lblFlagsRegister.setText("FLAGS Register: ");

        tblProgramableRegisters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProgramableRegisters);

        txtInstructionRegister.setText("jTextField5");
        txtInstructionRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstructionRegisterActionPerformed(evt);
            }
        });

        txtProgramCounter.setText("jTextField6");
        txtProgramCounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProgramCounterActionPerformed(evt);
            }
        });

        lblProgramableRegisters.setText("Programable Registers:");

        txtFlagsRegister.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInstructionRegister)
                            .addComponent(lblFlagsRegister))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInstructionRegister)
                            .addComponent(txtFlagsRegister)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProgramableRegisters)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProgramCounter)
                                .addGap(18, 18, 18)
                                .addComponent(txtProgramCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgramCounter)
                    .addComponent(txtProgramCounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstructionRegister)
                    .addComponent(txtInstructionRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFlagsRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFlagsRegister))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProgramableRegisters)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInstructionRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstructionRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructionRegisterActionPerformed

    private void txtProgramCounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProgramCounterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProgramCounterActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFlagsRegister;
    private javax.swing.JLabel lblInstructionRegister;
    private javax.swing.JLabel lblProgramCounter;
    private javax.swing.JLabel lblProgramableRegisters;
    private javax.swing.JTable tblProgramableRegisters;
    private javax.swing.JTextField txtFlagsRegister;
    private javax.swing.JTextField txtInstructionRegister;
    private javax.swing.JTextField txtProgramCounter;
    // End of variables declaration//GEN-END:variables

    
}
